config/routes.rb
Shop::Application.routes.draw do
  get "pages/home"

  root :to => 'pages#home'

  resources :products, only: [:show, :index]

  get 'search' => 'search#index'

  namespace :admin do
    resources :products
    resources :categories

  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
  has_and_belongs_to_many :products
end

app/models/manufacturer.rb
class Manufacturer < ActiveRecord::Base
  attr_accessible :name
  has_many :product_manufacturers
  has_many :products, through: :product_manufacturers
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :description, :model_no, :name, :price, :inventory, :image, :category_ids, :manufacturer_ids

  has_and_belongs_to_many :categories

  has_many :product_manufacturers
  has_many :manufacturers, through:  :product_manufacturers

  has_attached_file :image, :styles => {:medium => "300x300>", :thumb => "100x100>"}

  ## class methods

  def self.home_page_products
    order.sample(9)
  end

  def self.available
    where("inventory is not null and inventory > ?", 0)
  end

  # instance methods

  def related_products
    Product.order.sample(3) # we do not know yet
  end

  def in_stock?
    inventory.to_i > 0
  end


end

app/models/product_manufacturer.rb
class ProductManufacturer < ActiveRecord::Base
  attr_accessible :manufacturer_id, :product_id

  belongs_to :manufacturer
  belongs_to :product

end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
  #before_filter :admin_required
  layout  "admin"
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::AdminController
  # GET /products
  # GET /products.json
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to [:admin, @product], notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to [:admin, @product], notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to admin_products_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/model_controller.rb
class ModelController < ApplicationController
  def Category
  end

  def name
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @home_page_products = Product.home_page_products
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def show
    @product = Product.find(params[:id])
  end

  def index
    @title = "All products"
    @products = Product.all
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @title = "Search Results"
    @products = Product.where(name: params[:keywords])
    render "products/index"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/model_helper.rb
module ModelHelper
end

app/views/admin/products/_form.html.erb
<%= simple_form_for [:admin, @product], :html => {:multipart => true} do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :name %>
      <%= f.input :image %>
      <%= f.association :categories, as: :check_boxes %>
      <%= f.association :manufacturers, as: :check_boxes %>

      <%= f.input :description %>
      <%= f.input :inventory %>
      <%= f.input :price %>
      <%= f.input :model_no %>
    </div>

    <div class="form-actions">
      <%= f.button :submit %>
    </div>
<% end %>

app/views/admin/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @oroduct %> |
<%= link_to 'Back', admin_products_path %>

app/views/admin/products/index.html.erb
<h1>Listing products</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= link_to 'Show', [:admin, product] %></td>
        <td><%= link_to 'Edit', edit_admin_product_path(product) %></td>
        <td><%= link_to 'Destroy', [:admin, product], method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
  <% end %>
</table>

<br/>

<%= link_to 'New Product', new_admin_product_path %>

app/views/admin/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_products_path %>

app/views/admin/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @product.name %>
</p>

<p>
  <b>Categories:</b>
  <%= @product.categories.pluck(:name).join(', ') %>
</p>

<p>
  <b>Manufacturers:</b>
  <%= @product.manufacturers.pluck(:name).join(', ') %>
</p>


<%= link_to 'Edit', edit_admin_product_path(@product) %> |
<%= link_to 'Back', admin_products_path %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Admin</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="templatemo_body_wrapper">
  <div id="templatemo_wrapper">

    <div id="templatemo_header">
      <div id="site_title"><h1><a href="http://www.templatemo.com">Online Shoes Store</a></h1></div>
      <div class="cleaner"></div>
    </div>
    <!-- END of templatemo_header -->

    <div id="templatemo_menubar">
      <div id="top_nav" class="ddsmoothmenu">
        <ul>
          <li><%= link_to "Products", admin_products_path %></li>
          <li><%= link_to "Categories", admin_categories_path %></li>

        </ul>
        <br style="clear: left"/>
      </div>
      <!-- end of ddsmoothmenu -->
      <div id="templatemo_search">
        <%= form_tag "/search", id: "search_form", method: :get do %>
            <input type="text" value=" " name="keyword" id="keyword" title="keyword" onfocus="clearText(this)" onblur="clearText(this)" class="txt_field"/>
            <input type="submit" name="Search" value=" " alt="Search" id="searchbutton" title="Search" class="sub_btn"/>
        <% end %>
      </div>
    </div>
    <!-- END of templatemo_menubar -->

    <div id="templatemo_main">

      <%= yield %>

      <div class="cleaner"></div>
    </div>
    <!-- END of templatemo_main -->

    <div id="templatemo_footer">
      <p><a href="#">Home</a> | <a href="#">Products</a> | <a href="#">About</a> | <a href="#">FAQs</a> |
        <a href="#">Checkout</a> | <a href="#">Contact Us</a>
      </p>

      Copyright © 2072 <a href="#">Your Company Name</a> | Designed by
      <a href="http://www.templatemo.com" target="_parent">Free CSS Templates</a>

    </div>
    <!-- END of templatemo_footer -->

  </div>
  <!-- END of templatemo_wrapper -->
</div>
<!-- END of templatemo_body_wrapper -->

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shop</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="templatemo_body_wrapper">
  <div id="templatemo_wrapper">

    <div id="templatemo_header">
      <div id="site_title"><h1><a href="http://www.templatemo.com">Online Shoes Store</a></h1></div>
      <div id="header_right">
        <p>
          <a href="#">My Account</a> | <a href="#">My Wishlist</a> | <a href="#">My Cart</a> | <a href="#">Checkout</a>
          | <a href="#">Log In</a></p>

        <p>
          Shopping Cart: <strong>3 items</strong> ( <a href="shoppingcart.html">Show Cart</a> )
        </p>
      </div>
      <div class="cleaner"></div>
    </div>
    <!-- END of templatemo_header -->

    <div id="templatemo_menubar">
      <div id="top_nav" class="ddsmoothmenu">
        <ul>
          <li><a href="index.html" class="selected">Home</a></li>
          <li><a href="products.html">Products</a>
            <ul>
              <li><a href="http://www.templatemo.com/page/1">Sub menu 1</a></li>
              <li><a href="http://www.templatemo.com/page/2">Sub menu 2</a></li>
              <li><a href="http://www.templatemo.com/page/3">Sub menu 3</a></li>
              <li><a href="http://www.templatemo.com/page/4">Sub menu 4</a></li>
              <li><a href="http://www.templatemo.com/page/5">Sub menu 5</a></li>
            </ul>
          </li>
          <li><a href="about.html">About</a>
            <ul>
              <li><a href="http://www.templatemo.com/page/1">Sub menu 1</a></li>
              <li><a href="http://www.templatemo.com/page/2">Sub menu 2</a></li>
              <li><a href="http://www.templatemo.com/page/3">Sub menu 3</a></li>
            </ul>
          </li>
          <li><a href="faqs.html">FAQs</a></li>
          <li><a href="checkout.html">Checkout</a></li>
          <li><a href="contact.html">Contact Us</a></li>
        </ul>
        <br style="clear: left"/>
      </div>
      <!-- end of ddsmoothmenu -->


      <div >

      </div>
    </div>
    <!-- END of templatemo_menubar -->

    <div id="templatemo_main">
      <div id="sidebar" class="float_l">
        <div class="sidebar_box"><span class="bottom"></span>

          <h3>Categories</h3>

          <div class="content">
            <ul class="sidebar_list">
              <li class="first"><a href="#">Sed eget purus</a></li>
              <li><a href="#">Vestibulum eleifend</a></li>
              <li><a href="#">Nulla odio ipsum</a></li>
              <li><a href="#">Suspendisse posuere</a></li>
              <li><a href="#">Nunc a dui sed</a></li>
              <li><a href="#">Curabitur ac mauris</a></li>
              <li><a href="#">Mauris nulla tortor</a></li>
              <li><a href="#">Nullam ultrices</a></li>
              <li><a href="#">Nulla odio ipsum</a></li>
              <li><a href="#">Suspendisse posuere</a></li>
              <li><a href="#">Nunc a dui sed</a></li>
              <li><a href="#">Curabitur ac mauris</a></li>
              <li><a href="#">Mauris nulla tortor</a></li>
              <li><a href="#">Nullam ultrices</a></li>
              <li class="last"><a href="#">Sed eget purus</a></li>
            </ul>
          </div>
        </div>
        <div class="sidebar_box"><span class="bottom"></span>

          <h3>Bestsellers </h3>

          <div class="content">
            <div class="bs_box">
              <a href="#">
                <%= image_tag "templatemo_image_01.jpg" %>
              </a>
              <h4><a href="#">Donec nunc nisl</a></h4>

              <p class="price">$10</p>

              <div class="cleaner"></div>
            </div>
            <div class="bs_box">
              <a href="#"><%= image_tag "templatemo_image_01.jpg" %></a>
              <h4><a href="#">Lorem ipsum dolor sit</a></h4>

              <p class="price">$12</p>

              <div class="cleaner"></div>
            </div>
            <div class="bs_box">
              <a href="#"><%= image_tag "templatemo_image_01.jpg" %></a>
              <h4><a href="#">Phasellus ut dui</a></h4>

              <p class="price">$20</p>

              <div class="cleaner"></div>
            </div>
            <div class="bs_box">
              <a href="#"><%= image_tag "templatemo_image_01.jpg" %></a>
              <h4><a href="#">Vestibulum ante</a></h4>

              <p class="price">$8</p>

              <div class="cleaner"></div>
            </div>
          </div>
        </div>
      </div>
      <div id="content" class="float_r">
        <%= yield %>
      </div>
      <div class="cleaner"></div>
    </div>
    <!-- END of templatemo_main -->

    <div id="templatemo_footer">
      <p><a href="#">Home</a> | <a href="#">Products</a> | <a href="#">About</a> | <a href="#">FAQs</a> |
        <a href="#">Checkout</a> | <a href="#">Contact Us</a>
      </p>

      Copyright © 2072 <a href="#">Your Company Name</a> | Designed by
      <a href="http://www.templatemo.com" target="_parent">Free CSS Templates</a>

    </div>
    <!-- END of templatemo_footer -->

  </div>
  <!-- END of templatemo_wrapper -->
</div>
<!-- END of templatemo_body_wrapper -->

</body>
</html>

app/views/pages/home.html.erb
<%= form_tag search_url, method: :get do %>
    <%= text_field_tag :keyword %>

    <%= submit_tag("Submit", class: "sub_btn") %>
<% end %>

<div id="slider-wrapper">
  <div id="slider" class="nivoSlider">
    <%= image_tag "slider/01.jpg" %>
    <a href="#"><%= image_tag "slider/02.jpg" %></a>
    <%= image_tag "slider/03.jpg" %>
    <%= image_tag "slider/04.jpg", title: "#htmlcaption" %>
  </div>
  <div id="htmlcaption" class="nivo-html-caption">
    <strong>This</strong> is an example of a <em>HTML</em> caption with <a href="#">a link</a>.
  </div>
</div>
<script type="text/javascript" src="jquery.nivo.slider.pack.js"></script>
<script type="text/javascript">
    $(window).load(function () {
        $('#slider').nivoSlider();
    });
</script>
<h1>New Products</h1>

<%= render @home_page_products %>

app/views/products/_product.html.erb
<div class="product_box">
  <h3><%= product.name %></h3>
  <a href="productdetail.html"><%= image_tag product.image %></a>

  <p><%= truncate(product.description.to_s, length: 10) %></p>

  <p class="product_price"><%= number_to_currency product.price %></p>
  <a href="shoppingcart.html" class="addtocart"></a>
  <%= link_to "", product, class: "detail" %>
</div>

app/views/products/index.html.erb
<h1>New Products</h1>
<%= render @products %>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>

<div class="content_half float_l">
  <a rel="lightbox[portfolio]" href="images/product/10_l.jpg"><img src="images/product/10.jpg" alt="image"/></a>
</div>
<div class="content_half float_r">
  <table>
    <tr>
      <td width="160">Price:</td>
      <td><%= number_to_currency @product.price %></td>
    </tr>
    <tr>
      <td>Availability:</td>
      <td><%= @product.in_stock? ? "In Stock" : "Out of Stock" %></td>
    </tr>
    <tr>
      <td>Model:</td>
      <td><%= @product.model_no %></td>
    </tr>
    <tr>
      <td>Manufacturer:</td>
      <td>Apple</td>
    </tr>
    <tr>
      <td>Quantity</td>
      <td><input type="text" value="1" style="width: 20px; text-align: right"/></td>
    </tr>
  </table>
  <div class="cleaner h20"></div>
  <% if @product.in_stock? %>
      <a href="shoppingcart.html" class="addtocart"></a>
  <% else %>
      Notify me when the product is available:
  <input type="text">
  <% end %>
</div>
<div class="cleaner h30"></div>

<h5>Product Description</h5>

<p><%= @product.description %></p>

<div class="cleaner h50"></div>

<h3>Related Products</h3>
<% @product.related_products.each do |product| %>
    <div class="product_box no_margin_right">
      <a href="productdetail.html"><img src="images/product/03.jpg" alt=""/></a>

      <h3><%= product.name %></h3>

      <p class="product_price"><%= number_to_currency product.name %></p>
      <a href="shoppingcart.html" class="addtocart"></a>
      <%= link_to "", product, class: "detail" %>
    </div>
<% end %>